version: '3.5'

services:
  angular-service:
    container_name: angularcontaier
    build: ./
    working_dir: /usr/src/app
    volumes:
      - ../JwtAuth:/usr/src/app
    ports:
      - '4200:4200'
    command: >
      bash -c "npm install && npm start"

