version: 2
jobs:
  build:
    docker:
      # Declaring the use of the image
      - image: circleci/node:10.0
    steps:
      - checkout
      - run: echo "my firts test with circle ci"
      - run: npm install
workflows:
  version: 2
  workflow:
    jobs:
      - build
