version: 2
jobs:
  image:
    build:
      docker:
        # Declaring the use of the image
        - image: circleci/node:10.0
      steps:
        - checkout
        - run: echo "my firts test with circle ci"
workflow:
  version: 2
  compilation:
    jobs:
      - image
